#BNF+IAT 1.0 UTF-8;
!grammar command;

//声明槽---10月5号灯展使用
!slot <LastVoice>;
!slot <Maitian>;
!slot <Derog>;
!slot <Commend>;
!slot <Normal>;
//开始规则
!start <callStart>;

//具体的规则
<callStart>:
(<Maitian>[<LastVoice>])
|(<Derog>[<LastVoice>])
|(<Commend>[<LastVoice>])
|(<Normal>[<LastVoice>])
;

<Maitian>:全亮|全部打开|全部灯亮;
<Derog>:杀戮|奴役|独裁|专制|暴力|战争|囚禁|侵犯|欺骗|虐待|羞辱|背叛|伤害|歧视|剥削|诽谤|辱骂|殴打
|偷窃|折磨|强迫|镇压|侮辱|抢劫|强奸|禁锢|污染|虚假|愚蠢|傲慢|浪费|仇恨|贪婪|虚荣|冷漠|绝望|痛苦|极权
|屠杀|贪污|受贿|贿赂|伪造|劫持|欺诈|盗窃|奸淫|猥亵|拐卖|中伤|胁迫|剥夺|陷害|敲诈|勒索
|毒害|毒杀|诅咒|咒骂|亵渎|鄙视|掠夺|谩骂|诋毁|监禁|煽动|威胁|操纵|骚扰|扼杀|毁灭|破坏|侵害|侵占|压迫
|压制|压抑|诬告|绑架|杀人|侵略|游行|和谐|维稳|文革|监控|残酷|耻笑|审查|诈骗|虚伪|欺负|刻薄|阴险|狡猾
|狠毒|恐怖|自私|不公|偏见|肮脏|谎言|小气|嫉妒|官僚|投毒|造假|徇私|舞弊|诱骗|拐骗|阴谋|恶毒|贫困|贫穷
|灭绝|腐化|腐败|施暴|异化|残暴|暴行|驱逐|冷酷|愚昧|纳粹|王八|倔驴|笨猪|疯狗|鸡婆|白痴|蠢货|笨蛋|妈的
|婊子|混蛋|我操|我擦|我靠|畜生|恶霸|狗屁|走狗|弱智|可恶|可恨|憎恶|荒谬|荒诞|滥用|谗言|癌症|投降|暴动
|蔑视|可鄙|扭曲|败坏|懦夫|懦弱|暴戾|卑鄙|谵妄|恶魔|妖魔|摧残|魔鬼|罪恶|龃龉|轻蔑|可耻|贬低|人渣|愚钝
|自大|邪恶|谬误|罪犯|犯罪|凶狠|憎恨|霸权|地狱|丑陋|丑恶|炒作|耻辱|无知|拙劣|非礼|恶劣|放纵|教唆|撒谎
|阴毒|恶意|恶臭|恶棍|悲惨|谋杀|污秽|恶心|淫亵|贱民|迂腐|变态|无情|傀儡|木偶|流氓|淫秽|恐吓|奴隶|势利
|怨恨|玷污|篡改|暴君|不忠|绝情|噱头|报复|卑劣|堕落|狭隘|阴暗|骗子|叛徒|恐惧|工作|加班|抑郁|竞争|拆迁;

<Commend>:自由|和平|宽容|幽默|浪漫|善良|自然|平等|爱情|梦想|希望|反思|大海|怜悯|礼物
|信任|有趣|真实|正义|开心|音乐|温暖|艺术|想象|冒险|文学|阳光|朋友|知识|彩虹|小溪|鲜花|纯粹|春天|赞美|沟通
|分享|好玩|关心|自省|尊重|保护|捍卫|深情|博爱|情人|惊奇|好奇|喜悦|节约|安全|舞蹈|自信|无畏|大胆|勇敢|谦卑
|仁慈|美丽|智慧|拥抱|坦率|快乐|同情|勇气|友谊|梦幻|奇妙|公平|高兴|诚实|荣誉|喜欢|独立|独创|创造|理想|直觉
|公正|开放|豁达|激情|纯净|嬉戏|安静|热情|思想|美好|幸福|月亮|友情|亲情|善意|文明|文化|谢谢|蝴蝶|幻想|飞翔
|生命|热爱|优美|激励|樱花|温柔|诗意|真诚|靠谱|天才|成长|伙伴|恋爱|野马|人权|生长|理解|革命|谦虚|信念|交流
|激动|冲动|生活|远方|可爱|创新|炊烟|亲密|默契|学习|帮助|挑战|赞赏|珊瑚|创意|真挚|谦逊|民主|鼓励|进步|欣赏
|互助|大地|孤独|沉默|野兽|广场|坚持|从容|淡定|欢乐|微笑|朴素|呵护|爱护|散步|相爱|开明|行动|野心|奋斗|感谢
|认真|好客|进化|宽恕|坚韧|友好|珍惜|陪伴|支持|赠送|爱心|诚恳|乡村|云朵|寂静|森林|湖泊|冰川|草原|雪山|河流;

<Normal>:苹果|香蕉|荔枝|西瓜|榴莲|草莓|芒果|桂圆|空气|雨水|立春|惊蛰|春分|清明|谷雨|立夏|小满|芒种|夏至
|小暑|大暑|立秋|处暑|白露|秋分|寒露|霜降|立冬|小雪|大雪|冬至|小寒|大寒|投票|白羊|金牛|双子|巨蟹|狮子|处女|天秤|天蝎|射手
|摩羯|水瓶|双鱼|坚毅|多样|非凡|丰富|风格|混沌|关爱|活力|生动|喜人|自觉|真心|茉莉|诗歌|辽阔|曙光|杨柳|明月|青山|莲花|凤凰
|月光|绿色|牧场|歌唱|游泳|飞扬|翱翔|天空|飞鸟|摇滚|驰骋|律动|飘舞|飞舞|渴望|热切|神秘|牵手|激烈|迷离|魔力|缘分|相识|相知
|迷恋|约会|表白|信仰|美食|书籍|时光|亲吻|新生|写作|倾听|重逢|假期|放假|恋人|告白|昆虫|小草|山脉|滑雪|螃蟹|星光|星空|清新
|舒心|清香|稻田|甜美|甜蜜|积极|礼貌|青春|蛋糕|甜品|爱恋|热恋|花朵|海浪|微风|沙滩|浪花|琴声|跳舞|歌声|知音|舒适|可乐|勤劳
|土地|水牛|朴实|简朴|踏实|温和|勤奋|爸爸|妈妈|母亲|孩子|母爱|疼爱|无私|奉献|灯塔|港湾|牵挂|乡愁|小船|思乡|亲人|谦让|姐姐
|旋律|陶醉|创作|作曲|灵感|灵动|节奏|电子|说唱|古典|流行|爵士|活泼|好听|乐器|编曲|秘密|飞跃|悦动|超越|透明|轻盈|动力|憧憬
|向往|追求|运动|跑步|奔跑|健身|爬山|登山|流汗|放松|汗水|梦游|童年|体验|唱歌|婉转|感动|动听|动情|洪亮|天籁|动心|悦耳|愉悦
|年轮|时间|青涩|情书|关注|相思|情诗|花园|可口|香甜|享受|鲜美|甘甜|鲜嫩|慈祥|凝视|和睦|祥和|美满|温馨|亲切|情谊|哥们|知己
|大学|旅行|徒步|新奇|美景|火车|飞行|手信|阅读|看书|私密|书店|哲学|语言|文字|思考|发散|柴火|烤火|团结|童真|童趣|鸽子|世界
|记者|努力|升华|改善|改进|力量|攀登|毅力|画画|设计|温泉|治愈|治疗|舒服|烂漫|极地|极光|海豹|海狮|企鹅|海豚|天真|珍贵|宝贵
|蓝色|飞鱼|鲸鱼|帆船|高尚|幸运|正直|平静|满足|热诚|感激|自发|精彩|杰出|热心|愉快|博学|轻松|漂亮|宁静|大方|纯洁|成熟|轻柔
|聪颖|出色|聪慧|深厚|敏捷|冷静|敏锐|健康|良好|英勇|卓越|达观|别致|优良|优秀|优雅|精湛|直爽|平和|慷慨|坚强|宽厚|扎实|渊博
|厚道|风趣|柔和|魅力|感恩|进取|激进|专注|田园|人类|安慰|清晰|模糊|浑沌|承诺|自足|美味|好梦|梦境|可靠|尊严|荣耀|灵魂|兴趣
|爱好|洞察|勇猛|光辉|快活|年轻|差异|兴奋|难忘|涅槃|乐观|原始|观察|持久|隐私|主动|戏剧|韧性|伴侣|合作|触摸|变革|蓬勃|美德
|欢迎|奇迹|付出|缠绵|岁月|丰盈|前进|爱人|神采|潮汐|喜感|幻觉|悠闲|知足|怜惜|静谧|灿烂|沙漠|夏日|半山|丛林|浣熊|楼阁|林展;

//语气词
<LastVoice>:了|呢|么|吧|吗|啦|哦|呀|哟|呢你|吧你|啊你|咯|唉|嘛|你|呐|没|没啊|了啊|了么|哎|哈|有没有|为什么|点|好;
